# Generated by Django 4.1.3 on 2022-12-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_remove_employees_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='img',
            field=models.ImageField(default=1, upload_to='employees/photos/'),
            preserve_default=False,
        ),
    ]
